import type { IUniversityProfile } from "@/lib/types";

export const MOCK_UNIVERSITIES: IUniversityProfile[] = [
  {
    id: "uni_nu",
    name: "Nazarbayev University",
    country: "Kazakhstan",
    city: "Astana",
    logoUrl: undefined,
    heroImageUrl: undefined,
    worldRank: 360,
    fitScore: 92,
    fitScoreBreakdown: {
      academic: 94,
      language: 90,
      financial: 96,
      interest: 88,
    },
    tags: [
      "Research",
      "English-medium",
      "Government Scholarship",
      "STEM-focused",
      "Liberal Arts Core",
    ],
    programs: [
      {
        id: "uni_nu_cs_ba",
        name: "BSc in Computer Science",
        level: "bachelor",
        durationMonths: 48,
        tuitionUsdPerYear: 21500,
        language: "English",
        deliveryMode: "on-campus",
        field: "Computer Science",
        scholarshipAvailable: true,
      },
      {
        id: "uni_nu_eng_ba",
        name: "BEng in Electrical & Computer Engineering",
        level: "bachelor",
        durationMonths: 48,
        tuitionUsdPerYear: 21500,
        language: "English",
        deliveryMode: "on-campus",
        field: "Electrical Engineering",
        scholarshipAvailable: true,
      },
      {
        id: "uni_nu_sse_ms",
        name: "MSc in Data Science",
        level: "master",
        durationMonths: 24,
        tuitionUsdPerYear: 18000,
        language: "English",
        deliveryMode: "on-campus",
        field: "Data Science",
        scholarshipAvailable: true,
      },
    ],
  },
  {
    id: "uni_kbtu",
    name: "Kazakh-British Technical University",
    country: "Kazakhstan",
    city: "Almaty",
    logoUrl: undefined,
    heroImageUrl: undefined,
    worldRank: 720,
    fitScore: 84,
    fitScoreBreakdown: {
      academic: 82,
      language: 86,
      financial: 90,
      interest: 80,
    },
    tags: [
      "Industry Partnerships",
      "Energy & IT",
      "Bilingual",
      "Internship Pipeline",
    ],
    programs: [
      {
        id: "uni_kbtu_it_ba",
        name: "BSc in Information Systems",
        level: "bachelor",
        durationMonths: 48,
        tuitionUsdPerYear: 6800,
        language: "English",
        deliveryMode: "on-campus",
        field: "Information Systems",
        scholarshipAvailable: true,
      },
      {
        id: "uni_kbtu_ai_ba",
        name: "BSc in Artificial Intelligence",
        level: "bachelor",
        durationMonths: 48,
        tuitionUsdPerYear: 7200,
        language: "English",
        deliveryMode: "on-campus",
        field: "Artificial Intelligence",
        scholarshipAvailable: true,
      },
      {
        id: "uni_kbtu_petro_ba",
        name: "BEng in Petroleum Engineering",
        level: "bachelor",
        durationMonths: 48,
        tuitionUsdPerYear: 7400,
        language: "English",
        deliveryMode: "on-campus",
        field: "Petroleum Engineering",
        scholarshipAvailable: false,
      },
    ],
  },
  {
    id: "uni_kimep",
    name: "KIMEP University",
    country: "Kazakhstan",
    city: "Almaty",
    logoUrl: undefined,
    heroImageUrl: undefined,
    worldRank: 980,
    fitScore: 78,
    fitScoreBreakdown: {
      academic: 76,
      language: 88,
      financial: 78,
      interest: 70,
    },
    tags: ["Business", "American Curriculum", "English-medium", "MBA Track"],
    programs: [
      {
        id: "uni_kimep_bus_ba",
        name: "BSc in Business Administration",
        level: "bachelor",
        durationMonths: 48,
        tuitionUsdPerYear: 8200,
        language: "English",
        deliveryMode: "on-campus",
        field: "Business Administration",
        scholarshipAvailable: true,
      },
      {
        id: "uni_kimep_econ_ba",
        name: "BSc in Economics",
        level: "bachelor",
        durationMonths: 48,
        tuitionUsdPerYear: 8200,
        language: "English",
        deliveryMode: "on-campus",
        field: "Economics",
        scholarshipAvailable: true,
      },
    ],
  },
];

export function getMockUniversityById(
  id: string,
): IUniversityProfile | undefined {
  return MOCK_UNIVERSITIES.find((u) => u.id === id);
}
